services:
  db:
    image: postgres:16
    container_name: timp-prac3-db
    environment:
      POSTGRES_USER: timp
      POSTGRES_PASSWORD: timp
      POSTGRES_DB: timp_prac3
    ports:
      - "55432:5432"
    volumes:
      - ./01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql:ro
      - ./03_functions.sql:/docker-entrypoint-initdb.d/03_functions.sql:ro
      - ./04_triggers.sql:/docker-entrypoint-initdb.d/04_triggers.sql:ro
      - timp_prac3_data:/var/lib/postgresql/data

volumes:
  timp_prac3_data:
